
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package dairy_m;

import java.time.*;
import java.awt.event.ActionEvent;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

import javax.swing.JOptionPane;

/**
 *
 * @author 91975
 */
public class Add_Information extends javax.swing.JDialog {

    /**
     * Creates new form Add_Information
     */
    public Add_Information(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public Add_Information() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Add_Information dialog = new Add_Information(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        insert = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        Time = new javax.swing.JTextField();
        Date = new javax.swing.JTextField();
        Quantity = new javax.swing.JTextField();
        Type_of_Milk = new javax.swing.JTextField();
        Farmer_id = new javax.swing.JTextField();
        Fat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        back.setText("Back");
        back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 31, 68, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        jLabel1.setText("Add Information");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 20, 257, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 191, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("Time");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 191, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("Fat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 267, 86, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setText("Type of Milk");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, 26));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setText("Quantity");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 266, -1, 26));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setText("Farmer_ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, 26));

        insert.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        insert.setText("Insert");
        insert.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        getContentPane().add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 66, -1));

        clear.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, -1, -1));

        Time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeActionPerformed(evt);
            }

            private void TimeActionPerformed(ActionEvent evt) {
            }
        });
        getContentPane().add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 190, 133, 33));

        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }

            private void DateActionPerformed(ActionEvent evt) {
            }
        });
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 190, 133, 33));

        Quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityActionPerformed(evt);
            }

            private void QuantityActionPerformed(ActionEvent evt) {
            }
        });
        getContentPane().add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 266, 133, 33));
        getContentPane().add(Type_of_Milk, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 133, 33));
        getContentPane().add(Farmer_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 133, 33));
        getContentPane().add(Fat, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 266, 133, 33));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/new.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_insertActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dairy_management_system",
                    "root", "2412");
            String sql = "insert into farmer(type_of_milk, quantity, fat , farmer_id) values(?,?,?,?)";
            PreparedStatement pstmt = con.prepareStatement(sql);
            // pstmt.setInt(2, Integer.parseInt(Farmer_id.getText()));
            // pstmt.setString(2, Date.getText());
            // pstmt.setString(3, Time.getText());
            pstmt.setString(4, Type_of_Milk.getText());
            pstmt.setInt(5, Integer.parseInt(Quantity.getText()));
            pstmt.setInt(6, Integer.parseInt(Fat.getText()));
            pstmt.setInt(7, Integer.parseInt(Farmer_id.getText()));
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Insertion Successfull");
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, null, 0);
        }
    }// GEN-LAST:event_insertActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_clearActionPerformed
        Date.setText(null);
        Farmer_id.setText(null);
        Quantity.setText(null);
        Time.setText(null);
        Type_of_Milk.setText(null);
        Fat.setText(null);
    }// GEN-LAST:event_clearActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_dateActionPerformed

    private void milk_idActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_milk_idActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_milk_idActionPerformed

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_timeActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField4ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backActionPerformed
        Milk m = new Milk();
        dispose();
    }// GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Date;
    private javax.swing.JTextField Farmer_id;
    private javax.swing.JTextField Fat;
    private javax.swing.JTextField Quantity;
    private javax.swing.JTextField Time;
    private javax.swing.JTextField Type_of_Milk;
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
